(function(){
'use strict';
const VERSION='1.05',DEVELOPER='Сабир',CREATED='28.08.2026';
const CHANGES={'1.05':['Обновлён визуальный стиль интерфейса.','Добавлена тёмная тема с туманным лесом ночью.','Добавлена светлая тема — туманный лес на рассвете.','Добавлено переключение темы одним касанием в разделе «О приложении».','Красные акцентные элементы приведены к цвету логотипа и получили потёртую текстуру.'],'1.04':['Добавлен раздел «О приложении».','Добавлен журнал версий с датами и изменениями.'],'1.03':['Добавлена расширенная база предметов и нейтральных предметов.','Исправлены категории предметов, навигация и локальная загрузка изображений.'],'1.02':['Исправлены стабильность создания и сохранения сборок, фильтры и дерево закупки.'],'1.01':['Добавлена базовая версия редактора сборок и локального каталога.']};
const THEME_KEY='dota-assistant-theme';
window.DOTA_APP_INFO={VERSION,DEVELOPER,CREATED,CHANGES};window.showAbout=showAbout;window.showVersions=showVersions;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function getTheme(){return localStorage.getItem(THEME_KEY)==='light'?'light':'dark'}
function applyTheme(theme){theme=theme==='light'?'light':'dark';document.documentElement.dataset.theme=theme;document.body.setAttribute('data-theme',theme);localStorage.setItem(THEME_KEY,theme);const m=document.querySelector('meta[name="theme-color"]');if(m)m.content=theme==='light'?'#dfe7e7':'#080b10'}
function ensureTheme(){applyTheme(getTheme())}
function ensureStyles(){if(document.getElementById('about-app-styles'))return;const s=document.createElement('style');s.id='about-app-styles';s.textContent='body.modal-open{overflow:hidden!important}.modal{z-index:10000!important}.modal .sheet{position:relative;z-index:10001}.modal-open .bottom-nav{display:none!important}.about-sheet{max-height:92vh!important;overflow-y:auto!important;padding-bottom:24px!important}';document.head.appendChild(s)}
function modal(inner){ensureStyles();document.body.classList.add('modal-open');const root=document.getElementById('modal');if(!root)return;root.innerHTML='<div class="modal"><div class="sheet about-sheet">'+inner+'</div></div>'}
function showAbout(){ensureTheme();modal('<div class="sheet-head"><div><h3>О приложении</h3><div class="muted">Dota Assistant</div></div><button type="button" class="close" data-about-close>Закрыть</button></div><div class="about-card"><div class="about-row"><span>Версия:</span><strong>'+esc(VERSION)+'</strong></div><div class="about-row"><span>Разработчик:</span><strong>'+esc(DEVELOPER)+'</strong></div><div class="about-row"><span>Дата версии:</span><strong>'+esc(CREATED)+'</strong></div></div><button type="button" class="theme-toggle" data-theme-toggle><span>Тема интерфейса</span><span class="theme-state">'+(getTheme()==='dark'?'Тёмная':'Светлая')+' <span class="theme-icon">'+(getTheme()==='dark'?'☾':'☀')+'</span></span></button><button type="button" class="about-link" data-show-versions>Версии и изменения <span>›</span></button>')}
function showVersions(){const dates={'1.05':'28.08.2026','1.04':'27.08.2026','1.03':'26.08.2026','1.02':'26.08.2026','1.01':'26.08.2026'};const versions=Object.entries(CHANGES).map(function(pair){const v=pair[0],changes=pair[1];return '<div class="version-block"><div class="version-head"><strong>v'+esc(v)+'</strong><span>'+esc(dates[v])+'</span></div><ul>'+changes.map(function(x){return '<li>'+esc(x)+'</li>'}).join('')+'</ul></div>'}).join('');modal('<div class="sheet-head"><div><h3>Версии</h3><div class="muted">История изменений</div></div><button type="button" class="close" data-about-close>Закрыть</button></div>'+versions)}
document.addEventListener('click',function(e){if(e.target.closest('[data-about]')){e.preventDefault();showAbout();return}if(e.target.closest('[data-theme-toggle]')){applyTheme(getTheme()==='dark'?'light':'dark');showAbout();return}if(e.target.closest('[data-show-versions]')){showVersions();return}if(e.target.closest('[data-about-close]')){const r=document.getElementById('modal');if(r)r.innerHTML='';document.body.classList.remove('modal-open')}});
ensureStyles();ensureTheme();
})();
