/* Dota Assistant v1.06 — account/auth/cloud sync, no external SDK */
(()=>{
const URL='https://jnhmawezxclyrhzvttvc.supabase.co',KEY='sb_publishable_meuajVSmCCdCpGqeRvWcpQ_vat1Wjz2',LK='dota-assistant-v2',SK='dta-session-v1';
let session=null,user=null,syncing=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const headers=(auth=true)=>({'apikey':KEY,'Content-Type':'application/json',...(auth&&session?{Authorization:`Bearer ${session.access_token}`}:{})});
async function api(path,opt={}){const r=await fetch(URL+path,{...opt,headers:{...headers(opt.auth!==false),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||`HTTP ${r.status}`);return d}
function local(){try{return JSON.parse(localStorage.getItem(LK)||'{}')}catch{return {}}}
function builds(){const x=local();return Array.isArray(x.builds)?x.builds:[]}
function write(bs){const x=local();x.builds=bs;localStorage.setItem(LK,JSON.stringify(x))}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function box(html){const m=document.querySelector('#modal');if(!m)return;m.innerHTML=`<div class="auth-backdrop"><div class="auth-card">${html}</div></div>`;m.classList.add('auth-open')}
function close(){const m=document.querySelector('#modal');if(m){m.innerHTML='';m.classList.remove('auth-open')}}
function loginForm(err=''){box(`<div class="auth-head"><div><div class="auth-kicker">DOTA ASSISTANT</div><h2>Вход</h2></div><button class="auth-close" data-auth="close">×</button></div><label>Email<input id="ae" type="email" autocomplete="email"></label><label>Пароль<input id="ap" type="password" autocomplete="current-password"></label>${err?`<div class="auth-error">${esc(err)}</div>`:''}<button class="primary wide" data-auth="login">Войти</button><button class="auth-link" data-auth="signup">Создать аккаунт</button>`)}
function signupForm(err=''){box(`<div class="auth-head"><div><div class="auth-kicker">DOTA ASSISTANT</div><h2>Регистрация</h2></div><button class="auth-close" data-auth="close">×</button></div><label>Никнейм<input id="au" maxlength="30" autocomplete="username"></label><label>Email<input id="ae" type="email" autocomplete="email"></label><label>Пароль<input id="ap" type="password" autocomplete="new-password"></label>${err?`<div class="auth-error">${esc(err)}</div>`:''}<button class="primary wide" data-auth="signup-submit">Зарегистрироваться</button><button class="auth-link" data-auth="login-form">У меня уже есть аккаунт</button>`)}
async function login(){try{const email=document.querySelector('#ae')?.value.trim(),password=document.querySelector('#ap')?.value;if(!email||!password)return loginForm('Заполните email и пароль.');const d=await api('/auth/v1/token?grant_type=password',{method:'POST',auth:false,body:JSON.stringify({email,password})});session=d;user=d.user;localStorage.setItem(SK,JSON.stringify(session));close();patchSave();await sync();renderAccount()}catch(e){loginForm(e.message)}}
async function signup(){try{const username=document.querySelector('#au')?.value.trim(),email=document.querySelector('#ae')?.value.trim(),password=document.querySelector('#ap')?.value;if(!username||!email||!password)return signupForm('Заполните все поля.');if(password.length<6)return signupForm('Пароль должен содержать минимум 6 символов.');const d=await api('/auth/v1/signup',{method:'POST',auth:false,body:JSON.stringify({email,password,data:{username,display_name:username}})});if(d.access_token){session=d;user=d.user;localStorage.setItem(SK,JSON.stringify(session));await migrate();close();patchSave();renderAccount()}else loginForm('Аккаунт создан. Проверьте email для подтверждения, затем войдите.')}catch(e){signupForm(e.message)}}
async function refresh(){if(!session?.refresh_token)return false;try{const d=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',auth:false,body:JSON.stringify({refresh_token:session.refresh_token})});session=d;user=d.user;localStorage.setItem(SK,JSON.stringify(session));return true}catch{return false}}
async function migrate(){const bs=builds();if(!bs.length||!user)return;for(const b of bs){const row={user_id:user.id,name:b.name||'Моя сборка',hero:b.hero||null,role:b.role||null,data:b,is_favorite:!!b.is_favorite};if(uuid(b.id))row.id=b.id;try{await api('/rest/v1/builds',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)})}catch(e){console.error(e)}}await sync()}
async function sync(){if(!session||!user||syncing)return;syncing=true;try{const rows=await api('/rest/v1/builds?select=*&order=updated_at.desc');write(rows.map(r=>({...r.data,id:r.id,name:r.name||r.data?.name||'Моя сборка',hero:r.hero||r.data?.hero||'',role:r.role||r.data?.role||'1',is_favorite:!!r.is_favorite})));if(window.load)load();if(window.render)render()}catch(e){console.error('cloud sync',e)}finally{syncing=false}}
async function cloudSave(){if(!session||!user||syncing)return;for(const b of builds()){const row={user_id:user.id,name:b.name||'Моя сборка',hero:b.hero||null,role:b.role||null,data:b,is_favorite:!!b.is_favorite,updated_at:new Date().toISOString()};if(uuid(b.id))row.id=b.id;try{await api('/rest/v1/builds',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)})}catch(e){console.error('save',e)}}}
function patchSave(){if(window.__dtaSavePatched||typeof window.save!=='function')return;const old=window.save;window.save=function(){old();cloudSave()};window.__dtaSavePatched=true}
function account(){let b=document.querySelector('#accountButton'),host=document.querySelector('.app');if(!host)return;if(!b){b=document.createElement('button');b.id='accountButton';b.className='account-button';host.prepend(b)}b.textContent=user?`◉ ${user.user_metadata?.username||user.email?.split('@')[0]||'Аккаунт'}`:'◉ Войти';b.onclick=()=>user?profile():loginForm()}
function profile(){box(`<div class="auth-head"><div><div class="auth-kicker">АККАУНТ</div><h2>${esc(user?.user_metadata?.username||user?.email?.split('@')[0]||'Игрок')}</h2></div><button class="auth-close" data-auth="close">×</button></div><div class="auth-info">${esc(user?.email||'')}</div><div class="auth-stats">Ваши сборки сохраняются в облаке и доступны после входа с другого устройства.</div><button class="primary wide" data-auth="sync">Синхронизировать</button><button class="auth-link danger-link" data-auth="logout">Выйти</button>`)}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-auth]');if(!a)return;const x=a.dataset.auth;if(x==='close')close();else if(x==='login')await login();else if(x==='signup')signupForm();else if(x==='signup-submit')await signup();else if(x==='login-form')loginForm();else if(x==='sync'){await migrate();close()}else if(x==='logout'){session=null;user=null;localStorage.removeItem(SK);account();close()}});
async function init(){try{const s=JSON.parse(localStorage.getItem(SK)||'null');if(s){session=s;user=s.user;if(!(await refresh())){session=null;user=null;localStorage.removeItem(SK)}}if(user){patchSave();const r=await api('/rest/v1/builds?select=id&limit=1');if(!r.length&&builds().length)await migrate();else await sync()}account()}catch(e){console.error('auth init',e);account()}}
window.DTAuth={openLogin:loginForm,sync,getUser:()=>user};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();