/* Dota Assistant v1.06 — username/password accounts, cloud sync */
(()=>{
const URL='https://jnhmawezxclyrhzvttvc.supabase.co',KEY='sb_publishable_meuajVSmCCdCpGqeRvWcpQ_vat1Wjz2',LK='dota-assistant-v2',SK='dta-session-v2',AUTH=`${URL}/functions/v1/username-auth`;
let session=null,user=null,syncing=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const local=()=>{try{return JSON.parse(localStorage.getItem(LK)||'{}')}catch{return {}}};
const builds=()=>{const x=local();return Array.isArray(x.builds)?x.builds:[]};
const write=bs=>{const x=local();x.builds=bs;localStorage.setItem(LK,JSON.stringify(x))};
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const validUsername=v=>/^[a-zA-Z0-9_-]{3,20}$/.test(v);
async function auth(action,username,password){const r=await fetch(AUTH,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({action,username,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Ошибка авторизации (${r.status})`);return d}
async function db(path,opt={}){const r=await fetch(URL+path,{...opt,headers:{'apikey':KEY,'Content-Type':'application/json','Authorization':`Bearer ${KEY}`,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d}
function box(html){const m=document.querySelector('#modal');if(!m)return;m.innerHTML=`<div class="auth-backdrop"><div class="auth-card">${html}</div></div>`;m.classList.add('auth-open')}
function close(){const m=document.querySelector('#modal');if(m){m.innerHTML='';m.classList.remove('auth-open')}}
function loginForm(err=''){box(`<div class="auth-head"><div><div class="auth-kicker">DOTA ASSISTANT</div><h2>Вход</h2></div><button class="auth-close" data-auth="close">×</button></div><label>Логин<input id="au" maxlength="20" autocomplete="username"></label><label>Пароль<input id="ap" type="password" autocomplete="current-password"></label>${err?`<div class="auth-error">${esc(err)}</div>`:''}<button class="primary wide" data-auth="login">Войти</button><button class="auth-link" data-auth="signup">Создать аккаунт</button>`)}
function signupForm(err=''){box(`<div class="auth-head"><div><div class="auth-kicker">DOTA ASSISTANT</div><h2>Регистрация</h2></div><button class="auth-close" data-auth="close">×</button></div><label>Логин<input id="au" maxlength="20" autocomplete="username" placeholder="3–20 символов"></label><label>Пароль<input id="ap" type="password" autocomplete="new-password"></label>${err?`<div class="auth-error">${esc(err)}</div>`:''}<button class="primary wide" data-auth="signup-submit">Зарегистрироваться</button><button class="auth-link" data-auth="login-form">У меня уже есть аккаунт</button>`)}
async function login(){try{const username=document.querySelector('#au')?.value.trim(),password=document.querySelector('#ap')?.value;if(!validUsername(username)||!password)return loginForm('Введите корректный логин и пароль.');const d=await auth('login',username,password);session=d;user=d.user;localStorage.setItem(SK,JSON.stringify(session));close();await sync();renderAccount()}catch(e){loginForm(e.message)}}
async function signup(){try{const username=document.querySelector('#au')?.value.trim(),password=document.querySelector('#ap')?.value;if(!validUsername(username))return signupForm('Логин: 3–20 символов, только латинские буквы, цифры, _ или -.');if(password.length<6)return signupForm('Пароль должен содержать минимум 6 символов.');const d=await auth('register',username,password);user=d.user;session={token:d.token,user:d.user};localStorage.setItem(SK,JSON.stringify(session));await migrate();close();renderAccount()}catch(e){signupForm(e.message)}}
async function migrate(){const bs=builds();if(!bs.length||!user)return;for(const b of bs){const row={id:uuid(b.id)?b.id:undefined,user_id:user.id,name:b.name||'Моя сборка',hero:b.hero||null,role:b.role||null,data:b,is_favorite:!!b.is_favorite};if(!row.id)delete row.id;try{await db('/rest/v1/builds',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)})}catch(e){console.error('migrate',e)}}await sync()}
async function sync(){if(!session||!user||syncing)return;syncing=true;try{const rows=await db(`/rest/v1/builds?select=*&user_id=eq.${encodeURIComponent(user.id)}&order=updated_at.desc`);write(rows.map(r=>({...r.data,id:r.id,name:r.name||r.data?.name||'Моя сборка',hero:r.hero||r.data?.hero||'',role:r.role||r.data?.role||'1',is_favorite:!!r.is_favorite})));if(window.load)load();if(window.render)render()}catch(e){console.error('cloud sync',e)}finally{syncing=false}}
async function cloudSave(){if(!session||!user||syncing)return;for(const b of builds()){const row={id:uuid(b.id)?b.id:undefined,user_id:user.id,name:b.name||'Моя сборка',hero:b.hero||null,role:b.role||null,data:b,is_favorite:!!b.is_favorite,updated_at:new Date().toISOString()};if(!row.id)delete row.id;try{await db('/rest/v1/builds',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)})}catch(e){console.error('save',e)}}}
function patchSave(){if(window.__dtaSavePatched||typeof window.save!=='function')return;const old=window.save;window.save=function(){old();cloudSave()};window.__dtaSavePatched=true}
function renderAccount(){let b=document.querySelector('#accountButton'),host=document.querySelector('.app');if(!host)return;if(!b){b=document.createElement('button');b.id='accountButton';b.className='account-button';host.prepend(b)}b.textContent=user?`◉ ${esc(user.username||'Аккаунт')}`:'◉ Войти';b.onclick=()=>user?profile():loginForm()}
function profile(){box(`<div class="auth-head"><div><div class="auth-kicker">АККАУНТ</div><h2>${esc(user?.username||'Игрок')}</h2></div><button class="auth-close" data-auth="close">×</button></div><div class="auth-stats">Ваши сборки сохраняются в облаке и доступны после входа с другого устройства.</div><button class="primary wide" data-auth="sync">Синхронизировать</button><button class="auth-link danger-link" data-auth="logout">Выйти</button>`)}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-auth]');if(!a)return;const x=a.dataset.auth;if(x==='close')close();else if(x==='login')await login();else if(x==='signup')signupForm();else if(x==='signup-submit')await signup();else if(x==='login-form')loginForm();else if(x==='sync'){await migrate();close()}else if(x==='logout'){session=null;user=null;localStorage.removeItem(SK);renderAccount();close()}});
function init(){try{const s=JSON.parse(localStorage.getItem(SK)||'null');if(s?.user&&s?.token){session=s;user=s.user;patchSave();sync()}renderAccount()}catch(e){console.error('auth init',e);renderAccount()}}
window.DTAuth={openLogin:loginForm,sync,getUser:()=>user};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();