/* Dota Assistant v1.06 — username/password accounts + automatic cloud builds */
(()=>{
const AUTH='https://jnhmawezxclyrhzvttvc.supabase.co/functions/v1/username-auth-secure',LK='dota-assistant-v2',SK='dta-session-v2';
let session=null,user=null,syncing=false,writingRemote=false,syncTimer=null,pollTimer=null,lastFingerprint='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const local=()=>{try{return JSON.parse(localStorage.getItem(LK)||'{}')}catch{return {}}};
const builds=()=>{const x=local();return Array.isArray(x.builds)?x.builds:[]};
const fingerprint=bs=>JSON.stringify(bs.map(b=>({id:b.id,name:b.name,hero:b.hero,role:b.role,slots:b.slots,timeline:b.timeline,notes:b.notes,is_favorite:b.is_favorite})));
const write=bs=>{const x=local();x.builds=bs;writingRemote=true;localStorage.setItem(LK,JSON.stringify(x));writingRemote=false;lastFingerprint=fingerprint(bs)};
async function call(action,extra={}){const r=await fetch(AUTH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Ошибка (${r.status})`);return d}
function box(html){const m=document.querySelector('#modal');if(!m)return;m.innerHTML=`<div class="auth-backdrop"><div class="auth-card">${html}</div></div>`;m.classList.add('auth-open')}
function close(){const m=document.querySelector('#modal');if(m){m.innerHTML='';m.classList.remove('auth-open')}}
function loginForm(err=''){box(`<div class="auth-head"><div><div class="auth-kicker">DOTA ASSISTANT</div><h2>Вход</h2></div><button class="auth-close" data-auth="close">×</button></div><label>Логин<input id="au" maxlength="20" autocomplete="username"></label><label>Пароль<input id="ap" type="password" autocomplete="current-password"></label>${err?`<div class="auth-error">${esc(err)}</div>`:''}<button class="primary wide" data-auth="login">Войти</button><button class="auth-link" data-auth="signup">Создать аккаунт</button>`)}
function signupForm(err=''){box(`<div class="auth-head"><div><div class="auth-kicker">DOTA ASSISTANT</div><h2>Регистрация</h2></div><button class="auth-close" data-auth="close">×</button></div><label>Логин<input id="au" maxlength="20" autocomplete="username" placeholder="3–20 символов"></label><label>Пароль<input id="ap" type="password" autocomplete="new-password"></label>${err?`<div class="auth-error">${esc(err)}</div>`:''}<button class="primary wide" data-auth="signup-submit">Зарегистрироваться</button><button class="auth-link" data-auth="login-form">У меня уже есть аккаунт</button>`)}
async function login(){try{const username=document.querySelector('#au')?.value.trim(),password=document.querySelector('#ap')?.value;if(!/^[a-zA-Z0-9_-]{3,20}$/.test(username)||!password)return loginForm('Введите корректный логин и пароль.');const d=await call('login',{username,password});session=d;user=d.user;localStorage.setItem(SK,JSON.stringify(d));close();await syncFromCloud();renderAccount()}catch(e){loginForm(e.message)}}
async function signup(){try{const username=document.querySelector('#au')?.value.trim(),password=document.querySelector('#ap')?.value;if(!/^[a-zA-Z0-9_-]{3,20}$/.test(username))return signupForm('Логин: 3–20 символов, латиница, цифры, _ или -.');if(password.length<6)return signupForm('Пароль должен содержать минимум 6 символов.');const d=await call('register',{username,password});session=d;user=d.user;localStorage.setItem(SK,JSON.stringify(d));await uploadLocalToCloud();close();renderAccount()}catch(e){signupForm(e.message)}}
function rowFromBuild(b){return{id:/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(b.id||''))?b.id:undefined,name:b.name||'Моя сборка',hero:b.hero||null,role:b.role||null,data:b,is_favorite:!!b.is_favorite}}
async function uploadLocalToCloud(){if(!session?.token)return;const bs=builds();for(const b of bs){try{const d=await call('save_build',{token:session.token,build:rowFromBuild(b)});if(d.build?.id)b.id=d.build.id}catch(e){console.error('cloud save',e)}}write(bs);await syncFromCloud()}
async function syncFromCloud(){if(!session?.token||!user||syncing)return;syncing=true;try{const d=await call('list_builds',{token:session.token});const rows=Array.isArray(d.builds)?d.builds:[];write(rows.map(r=>({...r.data,id:r.id,name:r.name||r.data?.name||'Моя сборка',hero:r.hero||r.data?.hero||'',role:r.role||r.data?.role||'1',is_favorite:!!r.is_favorite})));if(window.load)load();if(window.render)render()}catch(e){console.error('cloud load',e)}finally{syncing=false}}
async function pushCurrentBuilds(){if(!session?.token||!user||syncing||writingRemote)return;const bs=builds(),fp=fingerprint(bs);if(fp===lastFingerprint)return;try{const remote=(await call('list_builds',{token:session.token})).builds||[],ids=new Set(bs.map(b=>String(b.id)));for(const r of remote){if(!ids.has(String(r.id)))await call('delete_build',{token:session.token,id:r.id})}const updated=[];for(const b of bs){const d=await call('save_build',{token:session.token,build:rowFromBuild(b)});updated.push(d.build?.id?{...b,id:d.build.id}:b)}write(updated)}catch(e){console.error('automatic cloud sync',e)}}
function scheduleCloudSync(){if(!session?.token||writingRemote)return;clearTimeout(syncTimer);syncTimer=setTimeout(pushCurrentBuilds,500)}
function patchLocalStorage(){if(window.__dtaStoragePatched)return;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(k===LK&&!writingRemote)scheduleCloudSync()};window.__dtaStoragePatched=true}
function startCloudWatch(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(session?.token&&!syncing)pushCurrentBuilds()},1500)}
function renderAccount(){let b=document.querySelector('#accountButton'),host=document.querySelector('.app');if(!host)return;if(!b){b=document.createElement('button');b.id='accountButton';b.className='account-button';host.prepend(b)}b.textContent=user?`◉ ${esc(user.username)}`:'◉ Войти';b.onclick=()=>user?profile():loginForm()}
function profile(){box(`<div class="auth-head"><div><div class="auth-kicker">АККАУНТ</div><h2>${esc(user.username)}</h2></div><button class="auth-close" data-auth="close">×</button></div><div class="auth-stats">Облачное сохранение включено. Сборки сохраняются автоматически.</div><button class="auth-link danger-link" data-auth="logout">Выйти</button>`)}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-auth]');if(!a)return;const x=a.dataset.auth;if(x==='close')close();else if(x==='login')await login();else if(x==='signup')signupForm();else if(x==='signup-submit')await signup();else if(x==='login-form')loginForm();else if(x==='logout'){try{await call('logout',{token:session?.token})}catch{}session=null;user=null;clearTimeout(syncTimer);clearInterval(pollTimer);localStorage.removeItem(SK);renderAccount();close()}});
function init(){patchLocalStorage();startCloudWatch();try{const s=JSON.parse(localStorage.getItem(SK)||'null');if(s?.user&&s?.token){session=s;user=s.user;syncFromCloud()}renderAccount()}catch(e){console.error(e);renderAccount()}}
window.DTAuth={openLogin:loginForm,sync:syncFromCloud,getUser:()=>user,renderAccount,saveBuild:async b=>{const d=await call('save_build',{token:session?.token,build:rowFromBuild(b)});return d.build},deleteBuild:async id=>call('delete_build',{token:session?.token,id})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();