(function(){
'use strict';
const KEY='dota-assistant-v2';
const read=()=>{try{return Object.assign({page:'home',builds:[],drafts:[],wards:[]},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return {page:'home',builds:[],drafts:[],wards:[]}}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let buildQ='',buildRole='Все';
function nav(){const s=read(),p=s.page;return `<nav class="bottom-nav" aria-label="Основная навигация">
<button class="nav-btn ${p==='home'?'active':''}" data-nav="home" aria-label="Главная"><span class="nav-icon">⌂</span></button>
<button class="nav-btn ${p==='builds'?'active':''}" data-nav="builds" aria-label="Сборки"><span class="nav-icon">▣</span></button>
<button class="nav-btn ${p==='draft'?'active':''}" data-nav="draft" aria-label="Драфт"><span class="nav-icon">♟</span></button>
<button class="nav-btn ${p==='wards'?'active':''}" data-nav="wards" aria-label="Варды"><span class="nav-icon">◉</span></button>
<button class="nav-btn ${p==='community'?'active':''}" data-nav="community" aria-label="Сообщество"><span class="nav-icon">♟</span></button>
</nav>`}
function bindNav(){document.querySelectorAll('.bottom-nav [data-nav]').forEach(b=>b.onclick=()=>{const page=b.dataset.nav;const s=read();s.page=page;write(s);if(page==='builds')return buildsPage();if(page==='community')return communityPage();window.location.reload()})}
window.nav=nav;window.bindNav=bindNav;
function card(b){const slots=Array.isArray(b.slots)?b.slots.slice(0,6):Array(6).fill('');return `<div class="build-card" data-name="${esc((b.name||'').toLowerCase())}" data-hero="${esc((b.hero||'').toLowerCase())}" data-role="${esc(b.role||'1')}"><h3 class="build-name">${esc(b.name||'Моя сборка')}</h3><div class="build-hero">${esc(b.hero||'')}</div><div class="build-meta">Позиция ${esc(b.role||'1')}</div><div class="mini-items">${slots.map(x=>`<div class="mini-slot">${x?imageTag(x):'+'}</div>`).join('')}</div><div class="card-actions"><button class="ghost" data-open-build="${esc(b.id)}">Открыть</button><button class="ghost danger" data-delete-build="${esc(b.id)}">Удалить</button></div></div>`}
function apply(){const q=buildQ.trim().toLowerCase();document.querySelectorAll('#buildGrid .build-card').forEach(c=>{const text=((c.dataset.name||'')+' '+(c.dataset.hero||''));c.style.display=(!q||text.includes(q))&&(buildRole==='Все'||c.dataset.role===buildRole)?'':'none'})}
window.buildsPage=function(){const s=read();const cards=s.builds.length?s.builds.map(card).join(''):`<div class="home-card"><h2>Нет сборок</h2><p>Создай первую сборку.</p></div>`;document.querySelector('#app').innerHTML=`<div class="app"><div class="top"><div class="brand">DOTA ASSISTANT</div><div class="title">Сборки</div><div class="sub">Твоя база билдов</div></div><button class="primary wide" onclick="openNewBuild()">+ Добавить сборку</button><div class="build-filters"><input class="field" id="buildSearch" placeholder="Поиск по названию сборки или герою..." value="${esc(buildQ)}"><div class="build-role-filter"><button data-role="Все" class="${buildRole==='Все'?'active':''}">Все</button>${['1','2','3','4','5'].map(r=>`<button data-role="${r}" class="${buildRole===r?'active':''}">${r}</button>`).join('')}</div></div><div class="build-grid" id="buildGrid">${cards}</div></div>${nav()}`;bindNav();document.querySelector('#buildSearch')?.addEventListener('input',e=>{buildQ=e.target.value;apply()});document.querySelectorAll('.build-role-filter button').forEach(b=>b.onclick=()=>{buildRole=b.dataset.role;document.querySelectorAll('.build-role-filter button').forEach(x=>x.classList.toggle('active',x===b));apply()});document.querySelectorAll('[data-open-build]').forEach(b=>b.onclick=()=>window.uiEditBuild?window.uiEditBuild(b.dataset.openBuild):window.editBuild?.(b.dataset.openBuild));document.querySelectorAll('[data-delete-build]').forEach(b=>b.onclick=()=>window.uiDeleteBuild?window.uiDeleteBuild(b.dataset.deleteBuild):window.deleteBuild?.(b.dataset.deleteBuild));apply()};
window.communityPage=function(){document.querySelector('#app').innerHTML=`<div class="app"><div class="top"><div class="brand">DOTA ASSISTANT</div><div class="title">Сообщество</div><div class="sub">Сборки игроков</div></div><div class="home-card community-placeholder"><h2>Сообщество</h2><p>Здесь появятся сборки других игроков, которыми можно будет поделиться и сохранить себе.</p><div class="muted">Авторизация и общая база сборок будут добавлены позже.</div></div></div>${nav()}`;bindNav()};
})();
