(function(){
'use strict';
const KEY='dota-assistant-v2';
const load=()=>{try{return Object.assign({page:'home',builds:[],drafts:[],wards:[]},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {page:'home',builds:[],drafts:[],wards:[]}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const escUI=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let uiHeroQuery='',uiHeroForSetup='',uiRole='1',uiTarget={type:null,index:null};
const stateUI=()=>load();
function normalizeBuild(b){b.slots=Array.isArray(b.slots)?b.slots:Array(9).fill('');b.slots=[...b.slots,...Array(9).fill('')].slice(0,9);b.timeline=Array.isArray(b.timeline)?b.timeline:[];b.timeline=b.timeline.map(x=>({item:x?.item||x?.name||'',time:x?.time||'00:00'}));while(b.timeline.length<4)b.timeline.push({item:'',time:'00:00'});return b}
function shellUI(content){const s=stateUI();document.querySelector('#app').innerHTML=`<div class="app">${content}</div>${typeof nav==='function'?nav():''}`;if(typeof bindNav==='function')bindNav()}
function currentBuild(id){return stateUI().builds.map(normalizeBuild).find(b=>b.id===id)}
function updateBuild(id,fn){const s=stateUI(),b=s.builds.map(normalizeBuild).find(x=>x.id===id);if(!b)return;fn(b);save(s)}
function buildCardUI(b){b=normalizeBuild(b);return `<div class="build-card"><h3 class="build-name">${escUI(b.name||'Моя сборка')}</h3><div class="build-hero">${escUI(b.hero)}</div><div class="build-meta">Позиция ${escUI(b.role||'1')}</div><div class="mini-items">${b.slots.slice(0,6).map(x=>`<div class="mini-slot">${x?imageTag(x):'+'}</div>`).join('')}</div><div class="card-actions"><button class="ghost" onclick="uiEditBuild('${escUI(b.id)}')">Открыть</button><button class="ghost danger" onclick="uiDeleteBuild('${escUI(b.id)}')">Удалить</button></div></div>`}
window.buildCard=buildCardUI;
window.buildsPage=function(){const s=stateUI();shellUI(`<div class="top"><div class="brand">DOTA ASSISTANT</div><div class="title">Сборки</div><div class="sub">Твоя база билдов</div></div><button class="primary wide" onclick="openNewBuild()">+ Добавить сборку</button><div style="height:12px"></div>${s.builds.length?`<div class="build-grid">${s.builds.map(buildCardUI).join('')}</div>`:`<div class="home-card"><h2>Нет сборок</h2><p>Создай первую сборку.</p></div>`}`)};
window.uiEditBuild=function(id){const b=currentBuild(id);if(!b)return;window.__uiSelectedId=id;const s=stateUI();s.page='buildEditor';save(s);window.renderEditor()};
window.uiDeleteBuild=function(id){if(!confirm('Удалить сборку?'))return;const s=stateUI();s.builds=s.builds.filter(x=>x.id!==id);save(s);render()};
function heroPicker(){const q=uiHeroQuery.toLowerCase();return HEROES.filter(h=>h.toLowerCase().includes(q)).map(h=>`<button onclick='uiHeroChosen(${JSON.stringify(h)})'>${imageTag(h,'hero')}<span>${escUI(h)}</span></button>`).join('')}
window.openNewBuild=function(){showModal(`<div class="sheet-head"><h3>Новая сборка</h3><button class="close" onclick="closeModal()">Закрыть</button></div><input class="search" id="heroSearch" placeholder="Найти героя..." value="${escUI(uiHeroQuery)}"><div class="hero-select">${heroPicker()}</div>`);setTimeout(()=>{const i=document.querySelector('#heroSearch');if(i){i.focus();i.setSelectionRange(i.value.length,i.value.length);i.oninput=()=>{uiHeroQuery=i.value;openNewBuild()}}},0)};
window.uiHeroChosen=function(hero){uiHeroForSetup=hero;uiRole='1';showModal(`<div class="sheet-head"><div><h3>Новая сборка</h3><div class="muted">${escUI(hero)}</div></div><button class="close" onclick="openNewBuild()">Назад</button></div><div class="form-label">Позиция</div><div class="position-select">${['1','2','3','4','5'].map(r=>`<button class="${uiRole===r?'active':''}" onclick="uiRole='${r}';uiHeroChosen(${JSON.stringify(hero)})">${r}</button>`).join('')}</div><button class="primary wide" onclick="uiCreateBuild(${JSON.stringify(hero)})">Создать сборку</button>`)};
window.uiCreateBuild=function(hero){const s=stateUI(),b={id:Date.now().toString(36)+Math.random().toString(36).slice(2),hero,role:uiRole,name:'Моя сборка',slots:Array(9).fill(''),timeline:[{item:'',time:'00:00'},{item:'',time:'00:00'},{item:'',time:'00:00'},{item:'',time:'00:00'}],notes:''};s.builds.push(b);s.page='buildEditor';save(s);closeModal();window.__uiSelectedId=b.id;window.renderEditor()};
function invSlot(x,i){return `<button class="inv-slot ${x?'filled':''}" draggable="true" ondragstart="uiInvDragStart(event,${i})" ondragover="event.preventDefault()" ondrop="uiInvDrop(event,${i})" onclick="uiInventorySlot(${i})">${x?imageTag(x):'+'}${x?'<span class="slot-x">×</span>':''}</button>`}
function timelineUI(b){return `<div class="timeline-wrap"><div class="timeline-row">${b.timeline.map((s,i)=>`<div class="timeline-node"><button class="timeline-item-slot ${s.item?'filled':''}" onclick="uiTimelineSlot(${i})">${s.item?imageTag(s.item):'<span>+</span>'}</button><input class="timeline-time" value="${escUI(s.time||'00:00')}" placeholder="00:00" aria-label="Время" oninput="uiTimelineTime(${i},this.value)">${b.timeline.length>4?`<button class="timeline-remove" onclick="uiRemoveTimeline(${i})">×</button>`:''}</div>`).join('')}<button class="timeline-add" onclick="uiAddTimeline()">+</button></div></div>`}
function itemChoicesUI(){const cats=itemCategory==='Все'?Object.keys(ITEMS):[itemCategory],q=itemQuery.toLowerCase();return cats.flatMap(c=>ITEMS[c]).filter(x=>x.toLowerCase().includes(q)).map(x=>`<button class="item-choice" onclick='uiPickItem(${JSON.stringify(x)})'>${imageTag(x)}<span class="item-name">${escUI(x)}</span></button>`).join('')}
window.renderEditor=function(){const s=stateUI(),b=s.builds.map(normalizeBuild).find(x=>x.id===window.__uiSelectedId)||s.builds.map(normalizeBuild).find(x=>x.id===s.lastSelectedBuildId);if(!b)return buildsPage();window.__uiSelectedId=b.id;save(s);shellUI(`<div class="page-head"><button class="back" onclick="state.page='builds';render()">‹</button><div><div class="brand">СБОРКА</div><h2>${escUI(b.hero)}</h2></div></div><input class="field" id="buildName" value="${escUI(b.name||'')}" placeholder="Название сборки"><div class="form-label">Позиция</div><div class="roles">${['1','2','3','4','5'].map(r=>`<button class="role ${b.role===r?'active':''}" onclick="uiRoleEdit('${r}')">${r}</button>`).join('')}</div><div class="form-label">Инвентарь · 6 слотов + 3 рюкзака</div><div class="inventory">${b.slots.map((x,i)=>invSlot(x,i)).join('')}<div class="backpack-label">РЮКЗАК</div></div><div class="form-label">Добавить предмет</div><div class="item-tools"><input class="field item-search" id="itemSearch" placeholder="Поиск предмета..." value="${escUI(itemQuery)}"><button class="ghost" onclick="itemQuery='';renderEditor()">Сброс</button></div><div class="categories"><button class="cat ${itemCategory==='Все'?'active':''}" onclick="itemCategory='Все';renderEditor()">Все</button>${Object.keys(ITEMS).map(c=>`<button class="cat ${itemCategory===c?'active':''}" onclick='itemCategory=${JSON.stringify(c)};renderEditor()'>${escUI(c)}</button>`).join('')}</div><div class="item-grid">${itemChoicesUI()}</div><div class="form-label">Дерево прогресса закупки</div>${timelineUI(b)}<div class="form-label">Заметки</div><textarea class="field" id="notes" rows="4" placeholder="Лайнинг, тайминги, условия покупки...">${escUI(b.notes||'')}</textarea><button class="primary savebar" onclick="uiSaveEditor()">Сохранить сборку</button>`);const si=document.querySelector('#itemSearch');if(si)si.oninput=()=>{itemQuery=si.value;renderEditor();const n=document.querySelector('#itemSearch');if(n){n.focus();n.setSelectionRange(n.value.length,n.value.length)}}};
window.uiInventorySlot=function(i){uiTarget={type:'inventory',index:i};itemQuery='';renderEditor()};window.uiTimelineSlot=function(i){uiTarget={type:'timeline',index:i};itemQuery='';renderEditor()};
window.uiPickItem=function(item){const s=stateUI(),b=s.builds.find(x=>x.id===window.__uiSelectedId);if(!b)return;normalizeBuild(b);if(uiTarget.type==='timeline')b.timeline[uiTarget.index].item=item;else if(uiTarget.type==='inventory')b.slots[uiTarget.index]=item;else return toast('Сначала нажми на слот');uiTarget={type:null,index:null};save(s);renderEditor()};
window.uiInvDragStart=function(e,i){e.dataTransfer.setData('ui-inv-slot',String(i));e.dataTransfer.effectAllowed='move'};window.uiInvDrop=function(e,i){e.preventDefault();const from=Number(e.dataTransfer.getData('ui-inv-slot'));if(!Number.isInteger(from))return;const s=stateUI(),b=s.builds.find(x=>x.id===window.__uiSelectedId);if(!b)return;normalizeBuild(b);[b.slots[from],b.slots[i]]=[b.slots[i],b.slots[from]];save(s);renderEditor()};
window.uiRoleEdit=function(r){updateBuild(window.__uiSelectedId,b=>b.role=r);renderEditor()};window.uiTimelineTime=function(i,v){updateBuild(window.__uiSelectedId,b=>b.timeline[i].time=v)};window.uiAddTimeline=function(){updateBuild(window.__uiSelectedId,b=>b.timeline.push({item:'',time:'00:00'}));renderEditor()};window.uiRemoveTimeline=function(i){updateBuild(window.__uiSelectedId,b=>{if(b.timeline.length>4)b.timeline.splice(i,1)});renderEditor()};window.uiSaveEditor=function(){const name=document.querySelector('#buildName')?.value.trim()||'Моя сборка',notes=document.querySelector('#notes')?.value||'';updateBuild(window.__uiSelectedId,b=>{b.name=name;b.notes=notes});toast('Сборка сохранена')};window.editBuild=window.uiEditBuild;window.createBuild=window.uiCreateBuild;
})();