(function(){
'use strict';
const KEY='dota-assistant-v2';
const getState=()=>{try{return Object.assign({page:'home',builds:[],drafts:[],wards:[]},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {page:'home',builds:[],drafts:[],wards:[]}}};
const putState=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let heroQ='',selectedHero='',selectedRole='1',target={type:null,index:null},itemQ='',itemCat='Все',buildQ='',buildRole='Все';
function norm(b){b.slots=Array.isArray(b.slots)?[...b.slots,...Array(9).fill('')].slice(0,9):Array(9).fill('');b.timeline=Array.isArray(b.timeline)?b.timeline.map(x=>({item:x?.item||x?.name||'',time:x?.time||'00:00'})):[];while(b.timeline.length<4)b.timeline.push({item:'',time:'00:00'});return b}
function saveBuild(id,fn){const s=getState(),b=s.builds.find(x=>x.id===id);if(!b)return;norm(b);fn(b);putState(s)}
function shell(c){document.querySelector('#app').innerHTML=`<div class="app">${c}</div>${typeof nav==='function'?nav():''}`;if(typeof bindNav==='function')bindNav()}
function heroPicker(){const q=heroQ.toLowerCase();return HEROES.filter(h=>h.toLowerCase().includes(q)).map(h=>`<button class="hero-choice" onclick='uiChooseHero(${JSON.stringify(h)})'>${imageTag(h,'hero')}<span>${esc(h)}</span></button>`).join('')}
window.openNewBuild=function(){showModal(`<div class="sheet-head"><h3>Новая сборка</h3><button class="close" onclick="closeModal()">Закрыть</button></div><input class="search" id="heroSearch" placeholder="Найти героя..." value="${esc(heroQ)}"><div class="hero-select">${heroPicker()}</div>`);setTimeout(()=>{const i=document.querySelector('#heroSearch');if(i){i.focus();i.setSelectionRange(i.value.length,i.value.length);i.oninput=()=>{heroQ=i.value;openNewBuild()}}},0)};
window.uiChooseHero=function(hero){selectedHero=hero;showModal(`<div class="sheet-head"><div><h3>Новая сборка</h3><div class="muted">${esc(hero)}</div></div><button class="close" onclick="openNewBuild()">Назад</button></div><div class="form-label">Позиция</div><div class="position-select">${['1','2','3','4','5'].map(r=>`<button class="${selectedRole===r?'active':''}" onclick="selectedRole='${r}';uiChooseHero(${JSON.stringify(hero)})">${r}</button>`).join('')}</div><button class="primary wide" onclick="uiCreateBuild(${JSON.stringify(hero)})">Создать сборку</button>`)};
window.uiCreateBuild=function(hero){const s=getState(),b={id:Date.now().toString(36)+Math.random().toString(36).slice(2),hero,role:selectedRole,name:'Моя сборка',slots:Array(9).fill(''),timeline:Array.from({length:4},()=>({item:'',time:'00:00'})),notes:''};s.builds.push(b);putState(s);closeModal();window.__uiSelectedId=b.id;renderEditor()};
function card(b){norm(b);return `<div class="build-card" data-name="${esc((b.name||'').toLowerCase())}" data-hero="${esc((b.hero||'').toLowerCase())}" data-role="${esc(b.role||'1')}"><h3 class="build-name">${esc(b.name||'Моя сборка')}</h3><div class="build-hero">${esc(b.hero)}</div><div class="build-meta">Позиция ${esc(b.role||'1')}</div><div class="mini-items">${b.slots.slice(0,6).map(x=>`<div class="mini-slot">${x?imageTag(x):'+'}</div>`).join('')}</div><div class="card-actions"><button class="ghost" onclick="uiEditBuild('${esc(b.id)}')">Открыть</button><button class="ghost danger" onclick="uiDeleteBuild('${esc(b.id)}')">Удалить</button></div></div>`}
function applyBuildFilter(){const q=buildQ.trim().toLowerCase();document.querySelectorAll('.build-card').forEach(c=>{const okQ=!q||(c.dataset.name||'').includes(q)||(c.dataset.hero||'').includes(q);const okR=buildRole==='Все'||c.dataset.role===buildRole;c.style.display=okQ&&okR?'':'none'});}
window.buildsPage=function(){const s=getState();shell(`<div class="top"><div class="brand">DOTA ASSISTANT</div><div class="title">Сборки</div><div class="sub">Твоя база билдов</div></div><button class="primary wide" onclick="openNewBuild()">+ Добавить сборку</button><div class="build-filters"><input class="field" id="buildSearch" placeholder="Поиск по названию сборки или герою..." value="${esc(buildQ)}"><div class="build-role-filter"><button class="${buildRole==='Все'?'active':''}" onclick="buildRole='Все';applyBuildFilter();document.querySelectorAll('.build-role-filter button').forEach(x=>x.classList.remove('active'));this.classList.add('active')">Все</button>${['1','2','3','4','5'].map(r=>`<button class="${buildRole===r?'active':''}" onclick="buildRole='${r}';applyBuildFilter();document.querySelectorAll('.build-role-filter button').forEach(x=>x.classList.remove('active'));this.classList.add('active')">${r}</button>`).join('')}</div></div><div class="build-grid" id="buildGrid">${s.builds.length?s.builds.map(card).join(''):`<div class="home-card"><h2>Нет сборок</h2><p>Создай первую сборку.</p></div>`}</div>`);const i=document.querySelector('#buildSearch');if(i)i.oninput=()=>{buildQ=i.value;applyBuildFilter()};applyBuildFilter()};
window.uiEditBuild=function(id){window.__uiSelectedId=id;renderEditor()};window.uiDeleteBuild=function(id){if(!confirm('Удалить сборку?'))return;const s=getState();s.builds=s.builds.filter(x=>x.id!==id);putState(s);buildsPage()};
function invSlot(x,i){return `<button class="inv-slot ${x?'filled':''}" draggable="true" ondragstart="uiInvDragStart(event,${i})" ondragover="event.preventDefault()" ondrop="uiInvDrop(event,${i})" onclick="uiInventorySlot(${i})">${x?imageTag(x):'+'}${x?'<span class="slot-x">×</span>':''}</button>`}
function itemCatalog(){const cats=itemCat==='Все'?Object.keys(ITEMS):[itemCat],q=itemQ.toLowerCase();return cats.flatMap(c=>ITEMS[c]).filter(x=>x.toLowerCase().includes(q)).map(x=>`<button class="item-choice" draggable="true" ondragstart='uiItemDragStart(event,${JSON.stringify(x)})' onclick='uiPickItem(${JSON.stringify(x)})'>${imageTag(x)}<span class="item-name">${esc(x)}</span></button>`).join('')}
function timeline(b){return `<div class="timeline-wrap"><div class="timeline-row">${b.timeline.map((x,i)=>`<div class="timeline-node"><button class="timeline-item-slot ${x.item?'filled':''}" ondragover="event.preventDefault()" ondrop="uiTimelineDrop(event,${i})" onclick="uiTimelineSlot(${i})">${x.item?imageTag(x.item):'<span>+</span>'}</button><input class="timeline-time" value="${esc(x.time||'00:00')}" placeholder="00:00" oninput="uiTimelineTime(${i},this.value)">${b.timeline.length>4?`<button class="timeline-remove" onclick="uiRemoveTimeline(${i})">×</button>`:''}</div>`).join('')}<button class="timeline-add" onclick="uiAddTimeline()">+</button></div></div>`}
window.renderEditor=function(){const s=getState(),b=s.builds.find(x=>x.id===window.__uiSelectedId);if(!b)return buildsPage();norm(b);putState(s);shell(`<div class="page-head"><button class="back" onclick="buildsPage()">‹</button><div><div class="brand">СБОРКА</div><h2>${esc(b.hero)}</h2></div></div><input class="field" id="buildName" value="${esc(b.name||'')}" placeholder="Название сборки"><div class="form-label">Позиция</div><div class="roles">${['1','2','3','4','5'].map(r=>`<button class="role ${b.role===r?'active':''}" onclick="uiRoleEdit('${r}')">${r}</button>`).join('')}</div><div class="form-label">Инвентарь · 6 слотов + 3 рюкзака</div><div class="inventory">${b.slots.map(invSlot).join('')}</div><div class="form-label">Добавить предмет</div><div class="item-tools"><input class="field item-search" id="itemSearch" placeholder="Поиск предмета..." value="${esc(itemQ)}"><button class="ghost" onclick="itemQ='';renderEditor()">Сброс</button></div><div class="categories"><button class="cat ${itemCat==='Все'?'active':''}" onclick="itemCat='Все';renderEditor()">Все</button>${Object.keys(ITEMS).map(c=>`<button class="cat ${itemCat===c?'active':''}" onclick='itemCat=${JSON.stringify(c)};renderEditor()'>${esc(c)}</button>`).join('')}</div><div class="item-grid">${itemCatalog()}</div><div class="form-label">Дерево прогресса закупки</div>${timeline(b)}<div class="form-label">Заметки</div><textarea class="field" id="notes" rows="4" placeholder="Лайнинг, тайминги, условия покупки...">${esc(b.notes||'')}</textarea><button class="primary savebar" onclick="uiSaveEditor()">Сохранить сборку</button>`);const i=document.querySelector('#itemSearch');if(i)i.oninput=()=>{itemQ=i.value;renderEditor();const n=document.querySelector('#itemSearch');if(n){n.focus();n.setSelectionRange(n.value.length,n.value.length)}}};
window.uiInventorySlot=function(i){target={type:'inventory',index:i};itemQ='';renderEditor()};window.uiTimelineSlot=function(i){target={type:'timeline',index:i};itemQ='';renderEditor()};
window.uiPickItem=function(item){const s=getState(),b=s.builds.find(x=>x.id===window.__uiSelectedId);if(!b)return;norm(b);if(target.type==='timeline')b.timeline[target.index].item=item;else if(target.type==='inventory')b.slots[target.index]=item;else return toast('Сначала нажми на слот');target={type:null,index:null};putState(s);renderEditor()};
window.uiItemDragStart=function(e,item){e.dataTransfer.setData('ui-item',item);e.dataTransfer.effectAllowed='copy'};window.uiTimelineDrop=function(e,i){e.preventDefault();const item=e.dataTransfer.getData('ui-item');if(!item)return;const s=getState(),b=s.builds.find(x=>x.id===window.__uiSelectedId);if(!b)return;norm(b);b.timeline[i].item=item;putState(s);renderEditor()};
window.uiInvDragStart=function(e,i){e.dataTransfer.setData('ui-inv-slot',String(i));e.dataTransfer.effectAllowed='move'};window.uiInvDrop=function(e,i){e.preventDefault();const from=Number(e.dataTransfer.getData('ui-inv-slot'));if(!Number.isInteger(from))return;const s=getState(),b=s.builds.find(x=>x.id===window.__uiSelectedId);if(!b)return;norm(b);[b.slots[from],b.slots[i]]=[b.slots[i],b.slots[from]];putState(s);renderEditor()};
window.uiRoleEdit=function(r){saveBuild(window.__uiSelectedId,b=>b.role=r);renderEditor()};window.uiTimelineTime=function(i,v){saveBuild(window.__uiSelectedId,b=>b.timeline[i].time=v)};window.uiAddTimeline=function(){saveBuild(window.__uiSelectedId,b=>b.timeline.push({item:'',time:'00:00'}));renderEditor()};window.uiRemoveTimeline=function(i){saveBuild(window.__uiSelectedId,b=>{if(b.timeline.length>4)b.timeline.splice(i,1)});renderEditor()};window.uiSaveEditor=function(){const name=document.querySelector('#buildName')?.value.trim()||'Моя сборка',notes=document.querySelector('#notes')?.value||'';saveBuild(window.__uiSelectedId,b=>{b.name=name;b.notes=notes});toast('Сборка сохранена')};
window.communityPage=function(){shell(`<div class="top"><div class="brand">DOTA ASSISTANT</div><div class="title">Сообщество</div><div class="sub">Сборки игроков</div></div><div class="home-card community-placeholder"><h2>Сообщество</h2><p>Здесь появятся сборки других игроков, которыми можно будет поделиться и сохранить себе.</p><div class="muted">Авторизация и общая база сборок будут добавлены позже.</div></div>`) };
window.nav=function(){return `<nav class="bottom-nav"><button onclick="window.location.reload()"><span>⌂</span><small>Главная</small></button><button onclick="buildsPage()"><span>▣</span><small>Сборки</small></button><button onclick="typeof draftPage==='function'?draftPage():toast('Раздел в разработке')"><span>♟</span><small>Драфт</small></button><button onclick="typeof wardsPage==='function'?wardsPage():toast('Раздел в разработке')"><span>◉</span><small>Варды</small></button><button class="nav-community" onclick="communityPage()"><span>♟</span><small>Сообщество</small></button></nav>`};
window.bindNav=function(){};
setTimeout(()=>{if(document.querySelector('#app')){try{if(getState().page==='builds')buildsPage()}catch(e){}}},0);
})();